export const fallbackLowValuationScan = {
  mode: "fallback",
  source: "内置低估值快照",
  updatedAt: "2026-07-06T00:00:00.000+08:00",
  riskFreeYield: 2.2,
  message: "低估值 API 不可用，当前展示内置快照。真实投资前需要刷新最新 PE/PB/股息率和财报。",
  methodology: [
    "盈利收益率 = 100 / PE，用来和无风险收益率比较。",
    "安全边际主要来自 PE/PB 历史分位、股息率和盈利收益率利差。",
    "博格公式思想：长期收益约等于股息率 + 盈利增长 + 估值变化。",
    "低估不等于买入；质量、盈利趋势、周期位置和逻辑风险会扣分。",
  ],
  results: [
    {
      candidateId: "style_dividend_lowvol",
      name: "红利低波",
      category: "风格",
      representativeIndex: "红利低波",
      representativeEtfs: ["512890", "515300"],
      pe: 8.5,
      pb: 0.95,
      pePercentile: 28,
      pbPercentile: 30,
      dividendYield: 4.8,
      earningsYield: 11.76,
      earningsYieldSpread: 9.56,
      roe: 10.8,
      valueScore: 74,
      qualityScore: 72,
      cycleScore: 70,
      logicRiskScore: 32,
      marginOfSafety: 67,
      score: 74,
      stage: "低估修复初期",
      statusKey: "watch",
      status: "低估观察",
      suggestedRatio: "观察仓0%-5%，等待盈利或资金确认",
      action: "先观察，等盈利修复或资金企稳后再提高",
      reason: "价格已有折价，但盈利周期或趋势确认还不充分。",
      evidence: {
        valuation: "PE/PB 分位 28%/30%，盈利收益率 11.8%，相对无风险收益率利差 9.6%。",
        dividend: "股息率 4.8%，ROE 10.8%，质量/盈利趋势 72/66 分。",
        cycle: "周期修复 70 分，趋势确认 48 分。",
        risk: "逻辑风险 32 分；需防范高股息拥挤、周期品盈利回落和利率上行。",
      },
      source: "内置低估值快照",
      updatedAt: "2026-07-06T00:00:00.000+08:00",
    },
    {
      candidateId: "style_dividend",
      name: "中证红利",
      category: "风格",
      representativeIndex: "中证红利",
      representativeEtfs: ["515080", "510880"],
      pe: 7.8,
      pb: 0.86,
      pePercentile: 24,
      pbPercentile: 22,
      dividendYield: 5.4,
      earningsYield: 12.82,
      earningsYieldSpread: 10.62,
      roe: 11.2,
      valueScore: 80,
      qualityScore: 68,
      cycleScore: 68,
      logicRiskScore: 36,
      marginOfSafety: 70,
      score: 75,
      stage: "低估左侧",
      statusKey: "watch",
      status: "低估观察",
      suggestedRatio: "观察仓0%-5%，等待盈利或资金确认",
      action: "先观察，等盈利修复或资金企稳后再提高",
      reason: "价格已有折价，但盈利周期或趋势确认还不充分。",
      evidence: {
        valuation: "PE/PB 分位 24%/22%，盈利收益率 12.8%，相对无风险收益率利差 10.6%。",
        dividend: "股息率 5.4%，ROE 11.2%，质量/盈利趋势 68/60 分。",
        cycle: "周期修复 68 分，趋势确认 42 分。",
        risk: "逻辑风险 36 分；红利不是无风险资产，资源、金融和公用事业盈利仍有周期性。",
      },
      source: "内置低估值快照",
      updatedAt: "2026-07-06T00:00:00.000+08:00",
    },
    {
      candidateId: "theme_baijiu",
      name: "白酒",
      category: "行业/主题",
      representativeIndex: "中证白酒",
      representativeEtfs: ["512690"],
      pe: 18,
      pb: 4,
      pePercentile: 18,
      pbPercentile: 28,
      dividendYield: 3,
      earningsYield: 5.56,
      earningsYieldSpread: 3.36,
      roe: 20,
      valueScore: 73,
      qualityScore: 70,
      cycleScore: 45,
      logicRiskScore: 68,
      marginOfSafety: 47,
      score: 59,
      stage: "低估左侧",
      statusKey: "trap",
      status: "便宜但需验证",
      suggestedRatio: "0%-3%跟踪，不因便宜重仓",
      action: "便宜但逻辑有瑕疵，只做验证清单",
      reason: "估值便宜，但需求、盈利或行业逻辑存在较大验证压力。",
      evidence: {
        valuation: "PE/PB 分位 18%/28%，盈利收益率 5.6%，相对无风险收益率利差 3.4%。",
        dividend: "股息率 3.0%，ROE 20.0%，质量/盈利趋势 70/42 分。",
        cycle: "周期修复 45 分，趋势确认 28 分。",
        risk: "逻辑风险 68 分；估值回落明显，但需求、库存、渠道价格和盈利增速仍需验证。",
      },
      source: "内置低估值快照",
      updatedAt: "2026-07-06T00:00:00.000+08:00",
    },
  ],
};
