export const lowValuationUniverse = [
  {
    candidateId: "style_dividend_lowvol",
    name: "红利低波",
    category: "风格",
    representativeIndex: "红利低波",
    representativeEtfs: ["512890", "515300"],
    pe: 8.5,
    pb: 0.95,
    pePercentile: 28,
    pbPercentile: 30,
    dividendYield: 4.8,
    roe: 10.8,
    qualityScore: 76,
    profitTrendScore: 66,
    cycleScore: 70,
    trendConfirmationScore: 48,
    liquidityScore: 82,
    logicRiskScore: 32,
    riskNote: "需防范高股息拥挤、周期品盈利回落和利率上行。",
    source: "内置估值样本，需用最新指数估值更新",
  },
  {
    candidateId: "style_dividend",
    name: "中证红利",
    category: "风格",
    representativeIndex: "中证红利",
    representativeEtfs: ["515080", "510880"],
    pe: 7.8,
    pb: 0.86,
    pePercentile: 24,
    pbPercentile: 22,
    dividendYield: 5.4,
    roe: 11.2,
    qualityScore: 70,
    profitTrendScore: 60,
    cycleScore: 68,
    trendConfirmationScore: 42,
    liquidityScore: 86,
    logicRiskScore: 36,
    riskNote: "红利不是无风险资产，资源、金融和公用事业盈利仍有周期性。",
    source: "内置估值样本，需用最新指数估值更新",
  },
  {
    candidateId: "theme_bank",
    name: "银行",
    category: "行业/主题",
    representativeIndex: "中证银行",
    representativeEtfs: ["512800", "515290"],
    pe: 5.8,
    pb: 0.58,
    pePercentile: 18,
    pbPercentile: 15,
    dividendYield: 5.7,
    roe: 10.6,
    qualityScore: 64,
    profitTrendScore: 54,
    cycleScore: 64,
    trendConfirmationScore: 50,
    liquidityScore: 82,
    logicRiskScore: 46,
    riskNote: "低估值背后可能包含净息差、地产链和资产质量压力。",
    source: "内置估值样本，需用最新指数估值更新",
  },
  {
    candidateId: "style_soedividend",
    name: "央企红利",
    category: "风格",
    representativeIndex: "央企红利",
    representativeEtfs: ["561580", "159332"],
    pe: 7.2,
    pb: 0.8,
    pePercentile: 22,
    pbPercentile: 20,
    dividendYield: 5.6,
    roe: 10.0,
    qualityScore: 66,
    profitTrendScore: 58,
    cycleScore: 72,
    trendConfirmationScore: 40,
    liquidityScore: 78,
    logicRiskScore: 40,
    riskNote: "央企红利受分红政策、资源价格和资金拥挤度影响较大。",
    source: "内置估值样本，需用最新指数估值更新",
  },
  {
    candidateId: "cn_hs300",
    name: "沪深300",
    category: "宽基",
    representativeIndex: "沪深300",
    representativeEtfs: ["510300", "159919"],
    pe: 12.0,
    pb: 1.25,
    pePercentile: 35,
    pbPercentile: 30,
    dividendYield: 2.8,
    roe: 10.4,
    qualityScore: 68,
    profitTrendScore: 55,
    cycleScore: 58,
    trendConfirmationScore: 55,
    liquidityScore: 95,
    logicRiskScore: 28,
    riskNote: "宽基低估可能持续较久，需要盈利周期和风险偏好配合。",
    source: "内置估值样本，需用最新指数估值更新",
  },
  {
    candidateId: "theme_baijiu",
    name: "白酒",
    category: "行业/主题",
    representativeIndex: "中证白酒",
    representativeEtfs: ["512690"],
    pe: 18.0,
    pb: 4.0,
    pePercentile: 18,
    pbPercentile: 28,
    dividendYield: 3.0,
    roe: 20.0,
    qualityScore: 82,
    profitTrendScore: 42,
    cycleScore: 45,
    trendConfirmationScore: 28,
    liquidityScore: 80,
    logicRiskScore: 68,
    riskNote: "估值回落明显，但需求、库存、渠道价格和盈利增速仍需验证。",
    source: "内置估值样本，需用最新指数估值更新",
  },
  {
    candidateId: "theme_consumption",
    name: "消费",
    category: "行业/主题",
    representativeIndex: "主要消费",
    representativeEtfs: ["159928", "510150"],
    pe: 20.0,
    pb: 2.5,
    pePercentile: 34,
    pbPercentile: 38,
    dividendYield: 2.2,
    roe: 11.5,
    qualityScore: 60,
    profitTrendScore: 46,
    cycleScore: 46,
    trendConfirmationScore: 35,
    liquidityScore: 76,
    logicRiskScore: 54,
    riskNote: "消费复苏偏慢时，低估可能演变成盈利下修。",
    source: "内置估值样本，需用最新指数估值更新",
  },
  {
    candidateId: "theme_healthcare",
    name: "医疗",
    category: "行业/主题",
    representativeIndex: "医疗",
    representativeEtfs: ["512170", "159828"],
    pe: 28.0,
    pb: 2.5,
    pePercentile: 26,
    pbPercentile: 24,
    dividendYield: 1.2,
    roe: 8.0,
    qualityScore: 54,
    profitTrendScore: 44,
    cycleScore: 52,
    trendConfirmationScore: 34,
    liquidityScore: 74,
    logicRiskScore: 62,
    riskNote: "医疗低估需要确认政策、集采、盈利和需求拐点。",
    source: "内置估值样本，需用最新指数估值更新",
  },
  {
    candidateId: "hk_tech",
    name: "恒生科技",
    category: "行业/主题",
    representativeIndex: "恒生科技",
    representativeEtfs: ["513180", "513130"],
    pe: 22.0,
    pb: 2.1,
    pePercentile: 36,
    pbPercentile: 32,
    dividendYield: 0.4,
    roe: 7.5,
    qualityScore: 58,
    profitTrendScore: 56,
    cycleScore: 60,
    trendConfirmationScore: 48,
    liquidityScore: 84,
    logicRiskScore: 56,
    riskNote: "港股科技受美元流动性、平台经济盈利和人民币汇率影响明显。",
    source: "内置估值样本，需用最新指数估值更新",
  },
  {
    candidateId: "cn_csi500",
    name: "中证500",
    category: "宽基",
    representativeIndex: "中证500",
    representativeEtfs: ["510500", "159922"],
    pe: 24.0,
    pb: 1.7,
    pePercentile: 40,
    pbPercentile: 35,
    dividendYield: 1.8,
    roe: 7.0,
    qualityScore: 52,
    profitTrendScore: 50,
    cycleScore: 55,
    trendConfirmationScore: 52,
    liquidityScore: 88,
    logicRiskScore: 42,
    riskNote: "中盘宽基需要经济复苏和盈利扩散配合。",
    source: "内置估值样本，需用最新指数估值更新",
  },
];
