export const mainlineUniverse = [
  {
    candidateId: "cn_hs300",
    name: "沪深300",
    category: "宽基",
    representativeIndex: "沪深300",
    representativeEtfs: ["510300", "159919"],
    securities: [{ secid: "1.000300", name: "沪深300" }],
    industryScore: 58,
    policyScore: 55,
    tags: ["核心资产", "宽基", "大盘"],
  },
  {
    candidateId: "cn_a500",
    name: "中证A500",
    category: "宽基",
    representativeIndex: "中证A500",
    representativeEtfs: ["560510", "159338"],
    securities: [{ secid: "1.000510", name: "中证A500" }],
    industryScore: 62,
    policyScore: 60,
    tags: ["宽基", "新核心资产"],
  },
  {
    candidateId: "cn_csi500",
    name: "中证500",
    category: "宽基",
    representativeIndex: "中证500",
    representativeEtfs: ["510500", "159922"],
    securities: [{ secid: "1.000905", name: "中证500" }],
    industryScore: 58,
    policyScore: 54,
    tags: ["宽基", "中盘"],
  },
  {
    candidateId: "cn_csi1000",
    name: "中证1000",
    category: "宽基",
    representativeIndex: "中证1000",
    representativeEtfs: ["512100", "159845"],
    securities: [{ secid: "1.000852", name: "中证1000" }],
    industryScore: 56,
    policyScore: 54,
    tags: ["宽基", "小盘"],
  },
  {
    candidateId: "cn_chinext",
    name: "创业板",
    category: "宽基",
    representativeIndex: "创业板指",
    representativeEtfs: ["159915"],
    securities: [{ secid: "0.399006", name: "创业板指" }],
    industryScore: 64,
    policyScore: 58,
    tags: ["成长", "高波动"],
  },
  {
    candidateId: "cn_star50",
    name: "科创50",
    category: "宽基",
    representativeIndex: "科创50",
    representativeEtfs: ["588000", "588080"],
    securities: [{ secid: "1.000688", name: "科创50" }],
    industryScore: 66,
    policyScore: 62,
    tags: ["硬科技", "高波动"],
  },
  {
    candidateId: "style_dividend",
    name: "红利",
    category: "风格",
    representativeIndex: "中证红利",
    representativeEtfs: ["515080", "510880"],
    securities: [{ secid: "1.000922", name: "中证红利" }, { secid: "1.510880", name: "红利ETF" }],
    industryScore: 66,
    policyScore: 58,
    tags: ["现金流", "防守"],
  },
  {
    candidateId: "style_dividend_lowvol",
    name: "红利低波",
    category: "风格",
    representativeIndex: "红利低波",
    representativeEtfs: ["512890", "515300"],
    securities: [{ secid: "1.512890", name: "红利低波ETF" }],
    industryScore: 68,
    policyScore: 60,
    tags: ["红利", "低波"],
  },
  {
    candidateId: "style_soedividend",
    name: "央企红利",
    category: "风格",
    representativeIndex: "央企红利",
    representativeEtfs: ["561580", "159332"],
    securities: [{ secid: "1.561580", name: "央企红利ETF" }],
    industryScore: 65,
    policyScore: 70,
    tags: ["央企", "分红"],
  },
  {
    candidateId: "style_value",
    name: "价值",
    category: "风格",
    representativeIndex: "价值风格",
    representativeEtfs: ["510030", "159905"],
    securities: [{ secid: "1.510030", name: "价值ETF" }],
    industryScore: 58,
    policyScore: 54,
    tags: ["低估值", "价值"],
  },
  {
    candidateId: "style_growth",
    name: "成长",
    category: "风格",
    representativeIndex: "成长风格",
    representativeEtfs: ["159967", "510050"],
    securities: [{ secid: "0.159967", name: "创业板成长ETF" }],
    industryScore: 62,
    policyScore: 55,
    tags: ["成长", "弹性"],
  },
  {
    candidateId: "theme_ai_compute",
    name: "AI算力",
    category: "行业/主题",
    representativeIndex: "人工智能/云计算/算力",
    representativeEtfs: ["159819", "515070", "516510"],
    securities: [{ secid: "0.159819", name: "人工智能ETF" }, { secid: "1.515070", name: "人工智能AIETF" }],
    industryScore: 82,
    policyScore: 76,
    tags: ["AI", "算力", "云计算"],
  },
  {
    candidateId: "theme_semiconductor",
    name: "半导体",
    category: "行业/主题",
    representativeIndex: "半导体",
    representativeEtfs: ["512480", "159995"],
    securities: [{ secid: "1.512480", name: "半导体ETF" }, { secid: "0.159995", name: "芯片ETF" }],
    industryScore: 76,
    policyScore: 78,
    tags: ["芯片", "国产替代"],
  },
  {
    candidateId: "theme_semiconductor_equipment",
    name: "半导体设备",
    category: "行业/主题",
    representativeIndex: "半导体设备/国产替代",
    representativeEtfs: ["159516", "561980", "588200", "512480"],
    securities: [
      { secid: "0.159516", name: "半导体设备ETF" },
      { secid: "1.561980", name: "半导体设备ETF" },
      { secid: "1.588200", name: "科创芯片ETF" },
      { secid: "1.512480", name: "半导体ETF" },
    ],
    industryScore: 84,
    policyScore: 84,
    tags: ["设备", "国产替代", "晶圆厂资本开支"],
  },
  {
    candidateId: "theme_advanced_packaging_hbm",
    name: "先进封装/HBM",
    category: "行业/主题",
    representativeIndex: "先进封装/HBM/封测材料",
    representativeEtfs: ["588200", "159995", "512480"],
    securities: [
      { secid: "1.588200", name: "科创芯片ETF" },
      { secid: "0.159995", name: "芯片ETF" },
      { secid: "1.512480", name: "半导体ETF" },
    ],
    industryScore: 82,
    policyScore: 78,
    tags: ["HBM", "先进封装", "AI芯片"],
  },
  {
    candidateId: "theme_cpo_comm",
    name: "CPO/通信",
    category: "行业/主题",
    representativeIndex: "通信/CPO",
    representativeEtfs: ["515880", "159695"],
    securities: [{ secid: "1.515880", name: "通信ETF" }, { secid: "0.159695", name: "通信ETF" }],
    industryScore: 78,
    policyScore: 68,
    tags: ["CPO", "光模块", "通信"],
  },
  {
    candidateId: "theme_liquid_cooling_power",
    name: "液冷/AI电力",
    category: "行业/主题",
    representativeIndex: "数据中心液冷/电力设备",
    representativeEtfs: ["159611", "561700", "516270"],
    securities: [
      { secid: "0.159611", name: "电力ETF" },
      { secid: "1.561700", name: "电力设备ETF" },
      { secid: "1.516270", name: "新能源ETF" },
    ],
    industryScore: 76,
    policyScore: 70,
    tags: ["液冷", "数据中心", "电力设备"],
  },
  {
    candidateId: "theme_software",
    name: "软件信创",
    category: "行业/主题",
    representativeIndex: "软件/信创",
    representativeEtfs: ["515230", "159852"],
    securities: [{ secid: "1.515230", name: "软件ETF" }, { secid: "0.159852", name: "软件ETF" }],
    industryScore: 68,
    policyScore: 75,
    tags: ["信创", "软件"],
  },
  {
    candidateId: "theme_innovative_drug",
    name: "创新药",
    category: "行业/主题",
    representativeIndex: "创新药",
    representativeEtfs: ["159992", "515120"],
    securities: [{ secid: "0.159992", name: "创新药ETF" }, { secid: "1.515120", name: "创新药ETF" }],
    industryScore: 70,
    policyScore: 64,
    tags: ["医药", "创新药"],
  },
  {
    candidateId: "theme_healthcare",
    name: "医疗",
    category: "行业/主题",
    representativeIndex: "医疗",
    representativeEtfs: ["512170", "159828"],
    securities: [{ secid: "1.512170", name: "医疗ETF" }, { secid: "0.159828", name: "医疗ETF" }],
    industryScore: 60,
    policyScore: 58,
    tags: ["医疗", "消费医疗"],
  },
  {
    candidateId: "theme_nev",
    name: "新能源车",
    category: "行业/主题",
    representativeIndex: "新能源车",
    representativeEtfs: ["515030", "159806"],
    securities: [{ secid: "1.515030", name: "新能源车ETF" }, { secid: "0.159806", name: "新能源车ETF" }],
    industryScore: 62,
    policyScore: 62,
    tags: ["新能源车", "汽车"],
  },
  {
    candidateId: "theme_pv",
    name: "光伏",
    category: "行业/主题",
    representativeIndex: "光伏",
    representativeEtfs: ["515790", "159857"],
    securities: [{ secid: "1.515790", name: "光伏ETF" }, { secid: "0.159857", name: "光伏ETF" }],
    industryScore: 54,
    policyScore: 56,
    tags: ["光伏", "新能源"],
  },
  {
    candidateId: "theme_power_equipment",
    name: "电力设备",
    category: "行业/主题",
    representativeIndex: "电力设备",
    representativeEtfs: ["159611", "561700"],
    securities: [{ secid: "0.159611", name: "电力ETF" }, { secid: "1.561700", name: "电力设备ETF" }],
    industryScore: 64,
    policyScore: 68,
    tags: ["电力", "设备"],
  },
  {
    candidateId: "theme_storage",
    name: "储能",
    category: "行业/主题",
    representativeIndex: "储能",
    representativeEtfs: ["159566", "516270"],
    securities: [{ secid: "1.516270", name: "新能源ETF" }],
    industryScore: 64,
    policyScore: 66,
    tags: ["储能", "电力"],
  },
  {
    candidateId: "theme_robot",
    name: "机器人",
    category: "行业/主题",
    representativeIndex: "机器人",
    representativeEtfs: ["562500", "159770"],
    securities: [{ secid: "1.562500", name: "机器人ETF" }, { secid: "0.159770", name: "机器人ETF" }],
    industryScore: 70,
    policyScore: 64,
    tags: ["机器人", "自动化"],
  },
  {
    candidateId: "theme_defense",
    name: "军工",
    category: "行业/主题",
    representativeIndex: "军工",
    representativeEtfs: ["512660", "512680"],
    securities: [{ secid: "1.512660", name: "军工ETF" }, { secid: "1.512680", name: "军工ETF" }],
    industryScore: 60,
    policyScore: 68,
    tags: ["军工", "高端制造"],
  },
  {
    candidateId: "theme_consumption",
    name: "消费",
    category: "行业/主题",
    representativeIndex: "主要消费",
    representativeEtfs: ["159928", "510150"],
    securities: [{ secid: "0.159928", name: "消费ETF" }, { secid: "1.510150", name: "消费ETF" }],
    industryScore: 56,
    policyScore: 58,
    tags: ["消费", "复苏"],
  },
  {
    candidateId: "theme_baijiu",
    name: "白酒",
    category: "行业/主题",
    representativeIndex: "中证白酒",
    representativeEtfs: ["512690"],
    securities: [{ secid: "1.512690", name: "酒ETF" }],
    industryScore: 52,
    policyScore: 48,
    tags: ["消费", "白酒"],
  },
  {
    candidateId: "theme_brokerage",
    name: "证券",
    category: "行业/主题",
    representativeIndex: "证券公司",
    representativeEtfs: ["512880", "159841"],
    securities: [{ secid: "1.512880", name: "证券ETF" }, { secid: "0.159841", name: "证券ETF" }],
    industryScore: 58,
    policyScore: 62,
    tags: ["券商", "风险偏好"],
  },
  {
    candidateId: "theme_nonferrous",
    name: "有色",
    category: "行业/主题",
    representativeIndex: "有色金属",
    representativeEtfs: ["512400", "159871"],
    securities: [{ secid: "1.512400", name: "有色金属ETF" }, { secid: "0.159871", name: "有色金属ETF" }],
    industryScore: 62,
    policyScore: 52,
    tags: ["资源", "周期"],
  },
  {
    candidateId: "theme_coal",
    name: "煤炭",
    category: "行业/主题",
    representativeIndex: "煤炭",
    representativeEtfs: ["515220"],
    securities: [{ secid: "1.515220", name: "煤炭ETF" }],
    industryScore: 58,
    policyScore: 50,
    tags: ["资源", "红利"],
  },
  {
    candidateId: "theme_export",
    name: "出海制造",
    category: "行业/主题",
    representativeIndex: "出海制造",
    representativeEtfs: ["159667", "159512"],
    securities: [{ secid: "0.159667", name: "工业母机ETF" }, { secid: "0.159512", name: "汽车零部件ETF" }],
    industryScore: 74,
    policyScore: 64,
    tags: ["出海", "制造"],
  },
  {
    candidateId: "hk_tech",
    name: "港股科技",
    category: "行业/主题",
    representativeIndex: "恒生科技",
    representativeEtfs: ["513180", "513130"],
    securities: [{ secid: "1.513180", name: "恒生科技ETF" }, { secid: "1.513130", name: "恒生科技ETF" }],
    industryScore: 66,
    policyScore: 58,
    tags: ["港股", "科技"],
  },
  {
    candidateId: "us_sp500",
    name: "标普500",
    category: "海外",
    representativeIndex: "S&P 500",
    representativeEtfs: ["513500", "0966"],
    securities: [{ secid: "1.513500", name: "标普500ETF" }],
    industryScore: 68,
    policyScore: 55,
    tags: ["美股", "核心宽基"],
  },
  {
    candidateId: "us_nasdaq100",
    name: "纳斯达克100",
    category: "海外",
    representativeIndex: "Nasdaq 100",
    representativeEtfs: ["513100", "159941"],
    securities: [{ secid: "1.513100", name: "纳指ETF" }, { secid: "0.159941", name: "纳指ETF" }],
    industryScore: 78,
    policyScore: 54,
    tags: ["美股", "AI", "科技"],
  },
  {
    candidateId: "global_developed",
    name: "全球/发达市场宽基",
    category: "海外",
    representativeIndex: "全球/发达市场",
    representativeEtfs: ["513500", "513030"],
    securities: [{ secid: "1.513500", name: "标普500ETF" }, { secid: "1.513030", name: "德国ETF" }],
    industryScore: 62,
    policyScore: 52,
    tags: ["全球", "分散"],
  },
];
