export const fallbackMainlineScan = {
  mode: "fallback",
  source: "内置快照",
  updatedAt: "2026-07-01T00:00:00.000+08:00",
  benchmark: "沪深300/中证全指代理",
  message: "公开行情暂不可用，当前展示内置快照。请刷新重试，或检查网络。",
  results: [
    {
      candidateId: "theme_ai_compute",
      name: "AI算力",
      category: "行业/主题",
      representativeIndex: "人工智能/云计算/算力",
      representativeEtfs: ["159819", "515070", "516510"],
      returns20: 7.8,
      returns60: 18.4,
      returns120: 31.2,
      volumeTrend: 86,
      turnoverTrend: 82,
      fundFlowProxy: 84,
      valuationPercentile: 82,
      heatScore: 84,
      score: 70,
      stage: "高热拥挤",
      status: "可小仓观察",
      suggestedSatelliteRatio: "卫星仓的20%-50%",
      action: "只低速参与，等待回调确认",
      reason: "资金和相对强弱较强，但估值热度已经偏高，不适合直接重仓。",
      evidence: {
        fund: "成交和资金代理指标较强，说明资金仍在关注。",
        strength: "20/60/120日收益均显著强于宽基，趋势仍在。",
        heat: "估值与交易热度偏高，追入风险上升。",
        policy: "AI基础设施仍是中长期产业方向，但短期进入业绩验证阶段。",
      },
      source: "内置快照",
      updatedAt: "2026-07-01T00:00:00.000+08:00",
    },
    {
      candidateId: "theme_semiconductor_equipment",
      name: "半导体设备",
      category: "行业/主题",
      representativeIndex: "半导体设备/国产替代",
      representativeEtfs: ["159516", "561980", "588200", "512480"],
      returns20: 6.2,
      returns60: 15.8,
      returns120: 28.6,
      volumeTrend: 78,
      turnoverTrend: 73,
      fundFlowProxy: 76,
      valuationPercentile: 74,
      heatScore: 72,
      score: 76,
      stage: "订单验证",
      status: "主线候选",
      suggestedSatelliteRatio: "卫星仓的50%-100%",
      action: "作为AI硬件上游扩散方向分批参与",
      reason: "产业位置更聚焦，资金和相对强弱较好，但仍需要订单和财报验证。",
      evidence: {
        fund: "成交趋势抬升，说明资金开始从宽泛AI向上游设备扩散。",
        strength: "中期收益强于宽基，具备阶段性主线特征。",
        heat: "热度偏高但未到极端拥挤，适合分批而不是一次性重仓。",
        policy: "受益于晶圆厂资本开支、国产替代和先进制程设备需求。",
      },
      source: "内置快照",
      updatedAt: "2026-07-01T00:00:00.000+08:00",
    },
    {
      candidateId: "theme_cpo_comm",
      name: "CPO/通信",
      category: "行业/主题",
      representativeIndex: "通信/CPO",
      representativeEtfs: ["515880", "159695"],
      returns20: 8.9,
      returns60: 21.1,
      returns120: 36.4,
      volumeTrend: 88,
      turnoverTrend: 85,
      fundFlowProxy: 87,
      valuationPercentile: 88,
      heatScore: 89,
      score: 66,
      stage: "高热拥挤",
      status: "过热等待",
      suggestedSatelliteRatio: "0%-20%",
      action: "不追高，等待热度回落",
      reason: "产业逻辑强，但成交和涨幅过热，短期安全边际不足。",
      evidence: {
        fund: "资金关注度很高，拥挤度也同步上升。",
        strength: "20/60/120日趋势强于宽基，但越强越要看价格。",
        heat: "热度和估值代理都处于高位，新增资金应降速。",
        policy: "AI集群高速互联需求清晰，但订单兑现和估值需要同步验证。",
      },
      source: "内置快照",
      updatedAt: "2026-07-01T00:00:00.000+08:00",
    },
    {
      candidateId: "theme_liquid_cooling_power",
      name: "液冷/AI电力",
      category: "行业/主题",
      representativeIndex: "数据中心液冷/电力设备",
      representativeEtfs: ["159611", "561700", "516270"],
      returns20: 3.8,
      returns60: 9.5,
      returns120: 18.2,
      volumeTrend: 67,
      turnoverTrend: 61,
      fundFlowProxy: 65,
      valuationPercentile: 60,
      heatScore: 54,
      score: 67,
      stage: "预期驱动",
      status: "可小仓观察",
      suggestedSatelliteRatio: "卫星仓的20%-50%",
      action: "作为AI基础设施扩散方向观察",
      reason: "逻辑开始从算力向电力和散热扩散，但资金证据还不如一线主线完整。",
      evidence: {
        fund: "资金有升温迹象，但还不是最强方向。",
        strength: "中期表现略强于宽基，需要继续确认。",
        heat: "热度尚可控，但主题纯度差异较大。",
        policy: "数据中心建设、电网投资和液冷渗透率是核心验证点。",
      },
      source: "内置快照",
      updatedAt: "2026-07-01T00:00:00.000+08:00",
    },
    {
      candidateId: "theme_power_equipment",
      name: "电力设备",
      category: "行业/主题",
      representativeIndex: "电力设备",
      representativeEtfs: ["159611", "561700"],
      returns20: 2.8,
      returns60: 7.6,
      returns120: 14.8,
      volumeTrend: 61,
      turnoverTrend: 57,
      fundFlowProxy: 59,
      valuationPercentile: 55,
      heatScore: 45,
      score: 64,
      stage: "预期驱动",
      status: "可小仓观察",
      suggestedSatelliteRatio: "低速产业增强",
      action: "可作为产业增强低速定投，不替代宽基主仓",
      reason: "确定性来自电网投资、AI电力需求和新型电力系统，但短期爆发力弱于热门成长主线。",
      evidence: {
        fund: "资金温和关注，没有明显拥挤。",
        strength: "中期表现略强于宽基，适合观察能否持续。",
        heat: "热度不高，适合低速而不是追涨。",
        policy: "电网改造、新能源消纳和数据中心电力配套构成长期需求。",
      },
      source: "内置快照",
      updatedAt: "2026-07-01T00:00:00.000+08:00",
    },
    {
      candidateId: "theme_export",
      name: "出海制造",
      category: "行业/主题",
      representativeIndex: "出海制造",
      representativeEtfs: ["159667", "159512"],
      returns20: 4.6,
      returns60: 11.3,
      returns120: 22.7,
      volumeTrend: 66,
      turnoverTrend: 65,
      fundFlowProxy: 66,
      valuationPercentile: 58,
      heatScore: 52,
      score: 73,
      stage: "业绩验证",
      status: "主线候选",
      suggestedSatelliteRatio: "卫星仓的50%-100%",
      action: "可作为主线卫星候选，按估值分批",
      reason: "趋势和产业验证较好，热度未到极端拥挤。",
      evidence: {
        fund: "资金代理指标稳步抬升，但没有极端拥挤。",
        strength: "中期相对强弱优于宽基，具备主线持续性。",
        heat: "估值热度处于中性偏高，仍需分批。",
        policy: "制造出海受益于全球供应链重构和企业盈利兑现。",
      },
      source: "内置快照",
      updatedAt: "2026-07-01T00:00:00.000+08:00",
    },
    {
      candidateId: "style_dividend_lowvol",
      name: "红利低波",
      category: "风格",
      representativeIndex: "红利低波",
      representativeEtfs: ["512890", "515300"],
      returns20: 2.3,
      returns60: 6.4,
      returns120: 12.6,
      volumeTrend: 62,
      turnoverTrend: 58,
      fundFlowProxy: 60,
      valuationPercentile: 54,
      heatScore: 50,
      score: 69,
      stage: "订单验证",
      status: "可小仓观察",
      suggestedSatelliteRatio: "卫星仓的20%-50%",
      action: "更适合作为防守增强，不替代成长主线",
      reason: "防守资金仍有配置需求，但弹性低于成长主线。",
      evidence: {
        fund: "资金流较稳定，适合防守仓配置。",
        strength: "上涨斜率温和，波动相对低。",
        heat: "热度中性，风险主要来自行业集中和分红持续性。",
        policy: "低利率和风险偏好下降时更有吸引力。",
      },
      source: "内置快照",
      updatedAt: "2026-07-01T00:00:00.000+08:00",
    },
  ],
};
