export const stockOpportunityUniverse = [
  {
    code: "600519",
    name: "贵州茅台",
    industry: "白酒消费",
    theme: "高端消费",
    qualityScore: 92,
    valuationRisk: 78,
    cycleScore: 48,
  },
  {
    code: "300750",
    name: "宁德时代",
    industry: "新能源",
    theme: "动力电池",
    qualityScore: 82,
    valuationRisk: 70,
    cycleScore: 58,
  },
  {
    code: "002594",
    name: "比亚迪",
    industry: "新能源车",
    theme: "出海制造",
    qualityScore: 80,
    valuationRisk: 68,
    cycleScore: 62,
  },
  {
    code: "601138",
    name: "工业富联",
    industry: "AI硬件",
    theme: "AI服务器",
    qualityScore: 74,
    valuationRisk: 76,
    cycleScore: 78,
  },
  {
    code: "300308",
    name: "中际旭创",
    industry: "光模块",
    theme: "CPO/AI网络",
    qualityScore: 76,
    valuationRisk: 82,
    cycleScore: 84,
  },
  {
    code: "300502",
    name: "新易盛",
    industry: "光模块",
    theme: "CPO/AI网络",
    qualityScore: 72,
    valuationRisk: 84,
    cycleScore: 84,
  },
  {
    code: "002371",
    name: "北方华创",
    industry: "半导体设备",
    theme: "国产替代",
    qualityScore: 80,
    valuationRisk: 78,
    cycleScore: 76,
  },
  {
    code: "688981",
    name: "中芯国际",
    industry: "半导体",
    theme: "晶圆制造",
    qualityScore: 66,
    valuationRisk: 72,
    cycleScore: 68,
  },
  {
    code: "603986",
    name: "兆易创新",
    industry: "半导体",
    theme: "存储周期",
    qualityScore: 68,
    valuationRisk: 70,
    cycleScore: 72,
  },
  {
    code: "300274",
    name: "阳光电源",
    industry: "电力设备",
    theme: "储能/逆变器",
    qualityScore: 78,
    valuationRisk: 66,
    cycleScore: 64,
  },
  {
    code: "601899",
    name: "紫金矿业",
    industry: "有色资源",
    theme: "铜金资源",
    qualityScore: 76,
    valuationRisk: 64,
    cycleScore: 76,
  },
  {
    code: "600900",
    name: "长江电力",
    industry: "公用事业",
    theme: "红利防守",
    qualityScore: 88,
    valuationRisk: 62,
    cycleScore: 52,
  },
  {
    code: "600036",
    name: "招商银行",
    industry: "银行",
    theme: "金融核心",
    qualityScore: 78,
    valuationRisk: 48,
    cycleScore: 46,
  },
  {
    code: "601318",
    name: "中国平安",
    industry: "保险",
    theme: "金融修复",
    qualityScore: 72,
    valuationRisk: 46,
    cycleScore: 48,
  },
  {
    code: "600030",
    name: "中信证券",
    industry: "证券",
    theme: "风险偏好",
    qualityScore: 66,
    valuationRisk: 58,
    cycleScore: 64,
  },
  {
    code: "600276",
    name: "恒瑞医药",
    industry: "创新药",
    theme: "医药创新",
    qualityScore: 80,
    valuationRisk: 64,
    cycleScore: 58,
  },
  {
    code: "000333",
    name: "美的集团",
    industry: "家电",
    theme: "制造出海",
    qualityScore: 84,
    valuationRisk: 54,
    cycleScore: 56,
  },
  {
    code: "002475",
    name: "立讯精密",
    industry: "消费电子",
    theme: "AI终端",
    qualityScore: 76,
    valuationRisk: 62,
    cycleScore: 66,
  },
  {
    code: "002415",
    name: "海康威视",
    industry: "安防AI",
    theme: "端侧AI",
    qualityScore: 74,
    valuationRisk: 52,
    cycleScore: 50,
  },
  {
    code: "601668",
    name: "中国建筑",
    industry: "建筑央企",
    theme: "央企红利",
    qualityScore: 66,
    valuationRisk: 42,
    cycleScore: 44,
  },
  {
    code: "002230",
    name: "科大讯飞",
    industry: "AI应用",
    theme: "大模型应用",
    qualityScore: 62,
    valuationRisk: 82,
    cycleScore: 78,
  },
  {
    code: "300418",
    name: "昆仑万维",
    industry: "AI应用",
    theme: "AI内容/应用",
    qualityScore: 54,
    valuationRisk: 86,
    cycleScore: 82,
  },
  {
    code: "300364",
    name: "中文在线",
    industry: "AI应用",
    theme: "AI内容",
    qualityScore: 48,
    valuationRisk: 88,
    cycleScore: 84,
  },
  {
    code: "002261",
    name: "拓维信息",
    industry: "算力应用",
    theme: "国产AI生态",
    qualityScore: 50,
    valuationRisk: 86,
    cycleScore: 82,
  },
  {
    code: "300476",
    name: "胜宏科技",
    industry: "PCB",
    theme: "AI服务器PCB",
    qualityScore: 66,
    valuationRisk: 80,
    cycleScore: 84,
  },
  {
    code: "002463",
    name: "沪电股份",
    industry: "PCB",
    theme: "AI服务器PCB",
    qualityScore: 72,
    valuationRisk: 78,
    cycleScore: 82,
  },
  {
    code: "300394",
    name: "天孚通信",
    industry: "光通信",
    theme: "光器件",
    qualityScore: 72,
    valuationRisk: 84,
    cycleScore: 86,
  },
  {
    code: "688256",
    name: "寒武纪",
    industry: "AI芯片",
    theme: "国产算力",
    qualityScore: 52,
    valuationRisk: 92,
    cycleScore: 88,
  },
  {
    code: "688041",
    name: "海光信息",
    industry: "AI芯片",
    theme: "国产CPU/GPU",
    qualityScore: 66,
    valuationRisk: 84,
    cycleScore: 82,
  },
  {
    code: "688012",
    name: "中微公司",
    industry: "半导体设备",
    theme: "刻蚀设备",
    qualityScore: 78,
    valuationRisk: 78,
    cycleScore: 78,
  },
  {
    code: "300604",
    name: "长川科技",
    industry: "半导体设备",
    theme: "测试设备",
    qualityScore: 62,
    valuationRisk: 80,
    cycleScore: 78,
  },
  {
    code: "688072",
    name: "拓荆科技",
    industry: "半导体设备",
    theme: "薄膜沉积",
    qualityScore: 64,
    valuationRisk: 82,
    cycleScore: 80,
  },
  {
    code: "300316",
    name: "晶盛机电",
    industry: "高端设备",
    theme: "半导体/光伏设备",
    qualityScore: 74,
    valuationRisk: 64,
    cycleScore: 62,
  },
  {
    code: "002050",
    name: "三花智控",
    industry: "机器人/汽零",
    theme: "机器人执行器",
    qualityScore: 78,
    valuationRisk: 72,
    cycleScore: 78,
  },
  {
    code: "002600",
    name: "领益智造",
    industry: "消费电子",
    theme: "AI终端/机器人",
    qualityScore: 58,
    valuationRisk: 76,
    cycleScore: 78,
  },
  {
    code: "300124",
    name: "汇川技术",
    industry: "工控机器人",
    theme: "工业自动化",
    qualityScore: 82,
    valuationRisk: 66,
    cycleScore: 68,
  },
  {
    code: "300024",
    name: "机器人",
    industry: "机器人",
    theme: "机器人本体",
    qualityScore: 48,
    valuationRisk: 84,
    cycleScore: 82,
  },
  {
    code: "002384",
    name: "东山精密",
    industry: "电子制造",
    theme: "AI终端/PCB",
    qualityScore: 62,
    valuationRisk: 70,
    cycleScore: 72,
  },
  {
    code: "300782",
    name: "卓胜微",
    industry: "射频芯片",
    theme: "AI终端",
    qualityScore: 64,
    valuationRisk: 72,
    cycleScore: 66,
  },
  {
    code: "300661",
    name: "圣邦股份",
    industry: "模拟芯片",
    theme: "半导体复苏",
    qualityScore: 70,
    valuationRisk: 70,
    cycleScore: 66,
  },
  {
    code: "688008",
    name: "澜起科技",
    industry: "存储接口",
    theme: "AI内存/HBM",
    qualityScore: 74,
    valuationRisk: 76,
    cycleScore: 78,
  },
  {
    code: "000938",
    name: "紫光股份",
    industry: "服务器网络",
    theme: "AI基础设施",
    qualityScore: 68,
    valuationRisk: 68,
    cycleScore: 72,
  },
  {
    code: "000977",
    name: "浪潮信息",
    industry: "服务器",
    theme: "AI服务器",
    qualityScore: 66,
    valuationRisk: 74,
    cycleScore: 78,
  },
  {
    code: "002049",
    name: "紫光国微",
    industry: "军工电子",
    theme: "特种芯片",
    qualityScore: 66,
    valuationRisk: 68,
    cycleScore: 64,
  },
  {
    code: "300395",
    name: "菲利华",
    industry: "军工材料",
    theme: "半导体/军工材料",
    qualityScore: 70,
    valuationRisk: 62,
    cycleScore: 66,
  },
  {
    code: "002179",
    name: "中航光电",
    industry: "军工电子",
    theme: "连接器",
    qualityScore: 78,
    valuationRisk: 58,
    cycleScore: 60,
  },
  {
    code: "002465",
    name: "海格通信",
    industry: "卫星通信",
    theme: "卫星互联网",
    qualityScore: 56,
    valuationRisk: 72,
    cycleScore: 76,
  },
  {
    code: "300045",
    name: "华力创通",
    industry: "卫星导航",
    theme: "卫星互联网",
    qualityScore: 44,
    valuationRisk: 88,
    cycleScore: 84,
  },
  {
    code: "300502",
    name: "新易盛",
    industry: "光模块",
    theme: "CPO/AI网络",
    qualityScore: 72,
    valuationRisk: 84,
    cycleScore: 84,
  },
];
